### ISSUE TITLE
sir ,i need your help

### ISSUE THREAD

**Issue by chenyusheng** [timgilbert/lein-classpath-jar#1]
i am using lein in my win10 pc and looking a way to solve the problem of 'error =206'
I don't understand which file I should this code :  {:user {:plugins [[lein-classpath-jar "0.1.0"]]}} ?
 if you can give me some guide it will be helpful,thanks a lot!

**Comment by timgilbert** [comment]
Hi @chenyusheng...

The file you want is the [leiningen user profile file](https://github.com/technomancy/leiningen/blob/stable/doc/PROFILES.md#default-profiles) which lives at `~/.lein/profiles.clj`.

On Windows your home directory will probably depend on your [`%USERPROFILE%`](https://www.computerhope.com/issues/ch000109.htm) value, so the location will probably be something like `C:\Users\MY_USER_NAME\.lein\profiles.clj`.

Hope this helps! Unfortunately I'm not currently running in a Windows environment so I may not be able to give you much more assistance than this.

**Comment by chenyusheng** [comment]
Hi @timgilbert 
thanks for your reply, it is very helpful. I has slove my issue now. My project is runing complete success!
